///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"
#include "wago_steppers.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CModule1 = {0x81e616f5,0xfb6d,0x4b91,{0xbf,0x1c,0x47,0x33,0xdd,0x98,0x80,0xa3}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

typedef struct _Module1Inputs
{
	UINT8 EK1002_BITS;
	struct wago_stepper_t wago_stepper_inputs0;
	struct wago_stepper_t wago_stepper_inputs1;
	struct wago_stepper_t wago_stepper_inputs2;

	/*uint8_t wago_stepper_inputs0[11];
	uint8_t wago_stepper_inputs1[11];
	uint8_t wago_stepper_inputs2[11];*/

} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	UINT8 EK2008_BITS;
	struct wago_stepper_t wago_stepper_outputs0;
	struct wago_stepper_t wago_stepper_outputs1;
	struct wago_stepper_t wago_stepper_outputs2;
	/*uint8_t wago_stepper_outputs0[11];
	uint8_t wago_stepper_outputs1[11];
	uint8_t wago_stepper_outputs2[11];*/
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
